# -*- coding: utf-8 -*-
# **************************************************************************
# *
# * Authors:     Scipion Team
# *
# * National Center of Biotechnology, CSIC, Spain
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
import shutil
from glob import glob
from os.path import basename
from pwem.protocols import EMProtocol
from pyseg.convert.convert import splitPysegStarFile
from pyseg.protocols.protocol_pre_seg import outputObjects as presegOutputObjects

from pyseg.utils import createStarDirectories, genOutSplitStarFileName
from pyworkflow.protocol import FloatParam, PointerParam, LEVEL_ADVANCED, BooleanParam, IntParam
from pyworkflow.utils import Message, moveFile
from scipion.constants import PYTHON
from tomo.protocols import ProtTomoBase
from tomo.protocols.protocol_base import ProtTomoImportAcquisition

from pyseg import Plugin
from pyseg.constants import GRAPHS_SCRIPT


class ProtPySegGraphs(EMProtocol, ProtTomoBase, ProtTomoImportAcquisition):
    """
    Analyzes membrane-associated graph representations generated from
    segmented tomographic membranes in order to characterize structural
    connectivity and spatial organization within cryo-electron tomography
    datasets.

    AI Generated:

    Graph Analysis (ProtPySegGraphs) — User Manual
        Overview

        The Graph Analysis protocol generates and analyzes graph-based
        representations of segmented membranes obtained from tomographic
        data. Its primary objective is to transform membrane-associated
        densities into organized network models that can later support
        filament tracing, particle localization, connectivity studies,
        and structural interpretation of membrane environments.

        In cryo-electron tomography workflows, graph representations are
        especially useful when studying crowded membrane regions where
        proteins, filaments, or macromolecular assemblies form complex
        spatial arrangements. Instead of treating membranes only as
        geometric surfaces, the protocol creates a structured network
        that captures local connectivity and density organization across
        the segmented region.

        Biological Context

        Biological membranes frequently contain heterogeneous molecular
        landscapes composed of membrane proteins, cytoskeletal elements,
        vesicle-associated complexes, and membrane-bound assemblies.
        Understanding the spatial relationships among these components is
        often difficult when relying solely on raw density maps or simple
        segmentations.

        The graph representation generated by this protocol provides a
        framework for identifying biologically meaningful structural
        paths and regions of connectivity. This is particularly valuable
        in studies involving vesicles, organelle membranes, trafficking
        systems, synaptic structures, or filament-associated membrane
        networks.

        The resulting graph structures are commonly used as intermediate
        datasets for downstream particle picking, filament analysis, or
        membrane topology exploration.

        Inputs and Workflow

        The protocol operates on membranes that were previously segmented
        and prepared during pre-segmentation stages. These segmented
        membrane regions define the spatial boundaries in which the graph
        analysis is performed.

        During execution, membrane-associated regions are divided into
        manageable processing packages. This organization improves
        computational stability and allows large tomographic datasets to
        be processed incrementally. Such an approach is particularly
        important in large-scale cryo-ET projects where hundreds or
        thousands of vesicles may need to be analyzed.

        The protocol generates graph outputs for each segmented membrane
        region independently and then stores the resulting graph-related
        metadata for later workflow stages.

        Gaussian Filtering and Signal Interpretation

        One of the key parameters in the protocol is the application of
        Gaussian filtering prior to graph generation. Biologically, this
        filtering stage helps suppress small noisy features while
        enhancing larger and more coherent structural patterns.

        Lower filtering values preserve fine structural details and may
        be useful when studying small membrane-associated complexes or
        highly detailed local architectures. However, insufficient
        smoothing may also increase graph complexity and sensitivity to
        noise.

        Higher filtering values generate simpler and less dense graph
        representations. These settings are often preferable for large
        particles such as ribosomes or for exploratory analyses where
        robustness and computational efficiency are more important than
        recovering the smallest structural details.

        Graph Density and Connectivity

        The protocol allows control over the density of vertices and the
        balance between vertices and edges inside membrane regions. These
        parameters determine how detailed or simplified the resulting
        graph representation becomes.

        Dense graphs can better capture subtle structural organization
        and fine membrane-associated pathways, but they also increase
        computational cost and may introduce unnecessary complexity.
        Sparse graphs are computationally more efficient and easier to
        interpret, although excessive simplification can remove
        biologically meaningful connectivity patterns.

        From a biological perspective, the ideal balance depends on the
        size and organization of the structures being analyzed. Highly
        crowded membrane systems may benefit from denser graph sampling,
        while large-scale membrane topology studies often require more
        simplified graph structures.

        Distance Constraints Relative to the Membrane

        The protocol also controls how far graph structures are allowed
        to extend from the membrane surface. This parameter is important
        because membrane-associated biological complexes are often
        concentrated within limited spatial neighborhoods.

        Restricting the maximum distance focuses the analysis on regions
        immediately adjacent to the membrane, improving specificity for
        membrane-bound assemblies. Increasing the allowed distance may
        capture peripheral or indirectly associated structures, although
        it can also introduce unrelated densities or noise.

        In practical biological workflows, moderate distance constraints
        are typically preferred to preserve relevant contextual
        information while avoiding excessive contamination from distant
        regions.

        Computational Organization and Large Datasets

        Tomographic membrane analysis frequently involves very large
        datasets that can be computationally demanding. The protocol
        addresses this challenge by processing vesicles and membrane
        regions in separate packages. This organization improves
        workflow robustness and facilitates recovery in case of
        interrupted executions.

        Users can additionally decide whether intermediate processing
        files should be preserved. Keeping intermediate files may help
        during troubleshooting or method development, whereas removing
        them minimizes storage requirements in production workflows.

        Outputs and Their Interpretation

        The protocol produces graph-based membrane representations that
        describe the structural organization of segmented membrane
        regions. These outputs can subsequently support particle
        localization, filament tracing, connectivity analysis, or
        membrane topology characterization.

        The resulting graph structures should not be interpreted as
        direct biological models by themselves. Instead, they provide a
        computational representation of spatial organization that helps
        guide downstream biological interpretation and quantitative
        analysis.

        Practical Recommendations

        For most biological applications, it is advisable to begin with
        moderate smoothing and default graph density parameters. If the
        resulting graphs appear excessively fragmented or noisy,
        increasing the Gaussian filtering level often improves
        robustness.

        When studying small membrane-associated complexes or fine local
        organization, users may prefer denser graph representations and
        shorter membrane distance constraints. Conversely, broader
        topological studies may benefit from simpler graph structures
        with stronger smoothing.

        Large datasets should generally be processed using smaller
        package sizes to improve execution stability and facilitate
        recovery after interruptions.

        Final Perspective

        Graph-based membrane analysis provides an important bridge
        between segmented tomographic densities and higher-level
        structural interpretation. By transforming membrane-associated
        regions into organized connectivity networks, the protocol
        enables more advanced studies of spatial organization,
        membrane-associated interactions, and structural topology within
        cryo-electron tomography datasets.
    """

    _label = 'graphs'

    # -------------------------- DEFINE param functions ----------------------
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._outStarDir = None
        self._inStarDir = None
        self.starFileList = None

    def _defineParams(self, form):
        """ Define the input parameters that will be used.
        Params:
            form: this is the form to be populated with sections and params.
        """
        # You need a params to belong to a section:
        form.addSection(label=Message.LABEL_INPUT)
        form.addParam('inSegProt', PointerParam,
                      pointerClass='ProtPySegPreSegParticles',
                      label='Pre segmentation',
                      important=True,
                      allowsNull=False,
                      help='Pointer to preseg protocol.')
        form.addParam('vesiclePkgSize', IntParam,
                      label='Vesicles packaging size',
                      allowsNull=False,
                      help='The input set of particles will be split into packages of N vesicles. Each package will '
                           'be processed as a different step, allowing to continue the execution from the last step in '
                           'case of the protocol fails. On the other hand, more packages implies more calls to PySeg, '
                           'which can affect to performance.')
        form.addParam('keepOnlyReqFiles', BooleanParam,
                      label='Keep only required files?',
                      default=True,
                      expertLevel=LEVEL_ADVANCED,
                      help='If set to No, all the intermediate Disperse program resulting directories '
                           'will be kept in the extra folder.')

        group = form.addGroup('Graphs parameters')
        group.addParam('sSig', FloatParam,
                       label='Sigma for gaussian filtering',
                       default=1,
                       allowsNull=False,
                       help='Sigma for Gaussian foltering input tomograms. It allows to smooth '
                            'small and irrelevant features and increases teh signal noise ratio (SNR). '
                            'Higher values will provide less dense graphs (lower execution time), so they should be '
                            'used when picking large particles, like ribosomes.')
        group.addParam('vDen', FloatParam,
                       label='Vertex density within membranes (nm³)',
                       default=0.0035,
                       allowsNull=False,
                       expertLevel=LEVEL_ADVANCED,
                       help='Vertex density within membranes. It allows to adjust simplification '
                            'adaptively for every tomogram.')
        group.addParam('vRatio', FloatParam,
                       label='Avg ratio vertex/edge of graph within membrane',
                       default=4,
                       allowsNull=False,
                       expertLevel=LEVEL_ADVANCED,
                       help='Averaged ratio vertex/edge in the graph within membrane.')
        group.addParam('maxLen', FloatParam,
                       label='Maximum distance to membrane (Å)',
                       allowsNull=False,
                       help='Maximum euclidean distance to membrane in Å.')
        form.addParallelSection(threads=4, mpi=0)

    def _insertAllSteps(self):
        self._initialize()
        for starFile in self.starFileList:
            self._insertFunctionStep(self.pysegGraphs, starFile)
        self._insertFunctionStep(self.removeUnusedFilesStep)

    def _initialize(self):
        # Generate directories for input and output star files
        # Split the input file into n (threads) files
        self._outStarDir, self._inStarDir = createStarDirectories(self._getExtraPath())
        self.starFileList = splitPysegStarFile(self._getPreSegStarFile(), self._inStarDir, j=self.vesiclePkgSize.get())

    def pysegGraphs(self, starFile):
        # Script called
        Plugin.runPySeg(self, PYTHON, self._getGraphsCommand(starFile))
        # Fils returns the same star file name, so it will be renamed to avoid overwriting
        moveFile(self._getExtraPath(basename(starFile)).replace('.star', '_mb_graph.star'),
                 genOutSplitStarFileName(self._outStarDir, starFile))

    def removeUnusedFilesStep(self):
        # Remove Disperse program intermediate result directories if requested
        if self.keepOnlyReqFiles.get():
            disperseDirs = glob(self._getExtraPath('disperse_*'))
            [shutil.rmtree(disperseDir) for disperseDir in disperseDirs]

    # --------------------------- INFO functions -----------------------------------
    def _summary(self):
        summaryMsg = []
        if self.isFinished():
            summaryMsg.append('Graphs were correctly generated.')

    # --------------------------- UTIL functions -----------------------------------
    def _getGraphsCommand(self, starFile):
        graphsCmd = ' '
        graphsCmd += '%s ' % Plugin.getHome(GRAPHS_SCRIPT)
        graphsCmd += '--inStar %s ' % starFile
        graphsCmd += '--outDir %s ' % self._getExtraPath()
        graphsCmd += '--pixelSize %s ' % (self._getSamplingRate()/10)  # PySeg requires it in nm
        graphsCmd += '--sSig %s ' % self.sSig.get()
        graphsCmd += '--vDen %s ' % self.vDen.get()
        graphsCmd += '--veRatio %s ' % self.vRatio.get()
        graphsCmd += '--maxLen %s ' % (self.maxLen.get()/10)  # PySeg requires it in nm
        graphsCmd += '-j %s ' % self.numberOfThreads.get()
        return graphsCmd

    def _getPreSegStarFile(self):
        return self.inSegProt.get().getPresegOutputFile(self.inSegProt.get().getVesiclesCenteredStarFile())

    def _getSamplingRate(self):
        inVesicles = getattr(self.inSegProt.get(), presegOutputObjects.vesicles.name)
        return inVesicles.getSamplingRate()
